application: tfburtonresume
version: 1
runtime: php
api_version: 1

handlers:
- url: /bundles
  static_dir: framework-standard-edition/web/bundles

- url: /favicon.ico
  static_files: framework-standard-edition/web/favicon.ico
  upload: framework-standard-edition/web/favicon.ico

- url: /.*
  script: framework-standard-edition/web/app_dev.php

