parameters:
#    resume.example.class: Tburton\ResumeBundle\Example

services:
#    resume.example:
#        class: %resume.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
