#Initially put the Resume site in a subdirectory
root:
  defaults:  { _controller: ResumeBundle:Default:index }
  path:      /

resume-About:
  defaults:  { _controller: ResumeBundle:Default:about }
  path:      /About

resume-Contact:
  defaults:  { _controller: ResumeBundle:Default:contact }
  path:      /Contact

resume-Admin:
  defaults:  { _controller: ResumeBundle:Admin:admin }
  path:      /Admin

#security points
resume-login:
  defaults: { _controller: ResumeBundle:Login:login }
  path:     /Login

#cover the systems default and alternate path

resume-login2:
  defaults: { _controller: ResumeBundle:Login:login }
  path:     /login

resume-login3:
  defaults: { _controller: ResumeBundle:Login:login }
  path:     /login_openid

resume-logout:
  defaults: { _controller: ResumeBundle:Login:logout }
  path:     /Logout

#file downloads
resume-doc:
  defaults:  { _controller: ResumeBundle:File:docx }
  path:      /Resume/docx

resume-html:
  defaults:  { _controller: ResumeBundle:File:html }
  path:      /Resume/html

resume-txt:
  defaults:  { _controller: ResumeBundle:File:txt }
  path:      /Resume/txt

resume-pdf:
  defaults:  { _controller: ResumeBundle:File:pdf }
  path:      /Resume/pdf

fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"
